/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Transaction {
  amount: Decimal | null;
  id: Generated<number>;
  timestamp: Date | null;
  type: string | null;
  userId: number;
}

export interface User {
  accountNumber: string;
  currentBalance: number | null;
  dateOfBirth: Date | null;
  email: string;
  firstName: string | null;
  id: Generated<number>;
  lastName: string | null;
  phoneNumber: string;
}

export interface DB {
  transactions: Transaction;
  users: User;
}
